use std::{fs, path::Path};

use indoc::formatdoc;
use syn::{File, Item, ItemImpl, ItemStruct};

#[derive(Debug)]
struct CommandInfo {
    struct_name: String,
    module_name: String,
}

fn main() {
    let commands_dir = Path::new("src/commands");
    let out_file = commands_dir.join("generated.rs");

    let mut commands = Vec::new();

    if commands_dir.exists() {
        for entry in fs::read_dir(commands_dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();

            if path.extension().and_then(|s| s.to_str()) == Some("rs") {
                let module_name = path.file_stem().unwrap().to_str().unwrap();

                if module_name == "mod" || module_name == "generated" {
                    continue;
                }

                if let Ok(file_commands) = find_commands_in_file(&path) {
                    for struct_name in file_commands {
                        commands.push(CommandInfo {
                            struct_name,
                            module_name: module_name.to_string(),
                        });
                    }
                }
            }
        }
    }

    // Generate the registration code
    let generated = generate_code(&commands);
    fs::write(&out_file, generated).unwrap();

    // Tell cargo to rerun if commands directory changes
    println!("cargo:rerun-if-changed=src/commands");
}

fn find_commands_in_file(path: &Path) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let content = fs::read_to_string(path)?;
    let ast: File = syn::parse_file(&content)?;

    let mut command_structs = Vec::new();

    // Find all structs that derive Parser
    let parser_structs: Vec<String> = ast
        .items
        .iter()
        .filter_map(|item| {
            if let Item::Struct(s) = item {
                if has_parser_derive(&s) {
                    return Some(s.ident.to_string());
                }
            }
            None
        })
        .collect();

    // Find all structs that implement CommandRunner
    let command_runner_impls: Vec<String> = ast
        .items
        .iter()
        .filter_map(|item| {
            if let Item::Impl(impl_item) = item {
                if implements_command_runner(impl_item) {
                    if let syn::Type::Path(type_path) = &*impl_item.self_ty {
                        if let Some(segment) = type_path.path.segments.last() {
                            return Some(segment.ident.to_string());
                        }
                    }
                }
            }
            None
        })
        .collect();

    // Find intersection: structs that both derive Parser AND implement CommandRunner
    for struct_name in &parser_structs {
        if command_runner_impls.contains(struct_name) {
            command_structs.push(struct_name.clone());
        } else {
            eprintln!(
                "Warning: {} in {} derives Parser but doesn't implement CommandRunner",
                struct_name,
                path.display()
            );
        }
    }

    // Check for structs that implement CommandRunner but don't derive Parser
    for struct_name in &command_runner_impls {
        if !parser_structs.contains(struct_name) {
            eprintln!(
                "Error: {} in {} implements CommandRunner but doesn't derive Parser",
                struct_name,
                path.display()
            );
        }
    }

    Ok(command_structs)
}

fn has_parser_derive(s: &ItemStruct) -> bool {
    s.attrs.iter().any(|attr| {
        if attr.path().is_ident("derive") {
            if let Ok(list) = attr.parse_args_with(
                syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
            ) {
                return list.iter().any(|path| {
                    path.segments
                        .last()
                        .is_some_and(|seg| seg.ident == "Parser")
                });
            }
        }
        false
    })
}

fn implements_command_runner(impl_item: &ItemImpl) -> bool {
    if let Some((_, trait_path, _)) = &impl_item.trait_ {
        return trait_path
            .segments
            .last()
            .is_some_and(|seg| seg.ident == "CommandRunner");
    }
    false
}

fn generate_code(commands: &[CommandInfo]) -> String {
    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs - do not edit!\n\n");

    // Generate module declarations
    for cmd in commands {
        output.push_str(&format!("pub mod {};\n", cmd.module_name));
    }
    output.push('\n');

    // Generate wrapper structs and registrations
    for cmd in commands {
        let wrapper_name = format!("{}Wrapper", cmd.struct_name);
        let cmd_const_name = format!("{}_CMD", cmd.struct_name.to_uppercase());
        let module = &cmd.module_name;
        let struct_name = &cmd.struct_name;

        output.push_str(&formatdoc! {"
            struct {wrapper_name};

            impl crate::command::Command for {wrapper_name} {{
                fn command(&self) -> clap::Command {{
                    <{module}::{struct_name} as clap::CommandFactory>::command()
                }}

                fn execute_from_matches(&self, matches: &clap::ArgMatches) -> anyhow::Result<()> {{
                    let cmd = <{module}::{struct_name} as clap::FromArgMatches>::from_arg_matches(matches)?;
                    <{module}::{struct_name} as crate::command::CommandRunner>::run(cmd)
                }}
            }}

            #[linkme::distributed_slice(crate::command::COMMANDS)]
            static {cmd_const_name}: &'static dyn crate::command::Command = &{wrapper_name};

        "});
    }

    output
}
